use core::fmt::Debug;

/// Enumeration of Mobile Equipment errors, as defined in 3GPP TS 27.007
/// v17.1.0, section 9.2 (Mobile termination error result code +CME ERROR).
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum CmeError {
    /// nick=PhoneFailure
    PhoneFailure = 0,
    /// nick=NoConnection
    NoConnection = 1,
    /// nick=LinkReserved
    LinkReserved = 2,
    /// nick=NotAllowed
    NotAllowed = 3,
    /// nick=NotSupported
    NotSupported = 4,
    /// nick=PhSimPin
    PhSimPin = 5,
    /// nick=PhFsimPin
    PhFsimPin = 6,
    /// nick=PhFsimPuk
    PhFsimPuk = 7,
    /// nick=SimNotInserted
    SimNotInserted = 10,
    /// nick=SimPin
    SimPin = 11,
    /// nick=SimPuk
    SimPuk = 12,
    /// nick=SimFailure
    SimFailure = 13,
    /// nick=SimBusy
    SimBusy = 14,
    /// nick=SimWrong
    SimWrong = 15,
    /// nick=IncorrectPassword
    IncorrectPassword = 16,
    /// nick=SimPin2
    SimPin2 = 17,
    /// nick=SimPuk2
    SimPuk2 = 18,
    /// nick=MemoryFull
    MemoryFull = 20,
    /// nick=InvalidIndex
    InvalidIndex = 21,
    /// nick=NotFound
    NotFound = 22,
    /// nick=MemoryFailure
    MemoryFailure = 23,
    /// nick=TextTooLong
    TextTooLong = 24,
    /// nick=InvalidChars
    InvalidChars = 25,
    /// nick=DialStringTooLong
    DialStringTooLong = 26,
    /// nick=DialStringInvalid
    DialStringInvalid = 27,
    /// nick=NoNetwork
    NoNetwork = 30,
    /// nick=NetworkTimeout
    NetworkTimeout = 31,
    /// nick=NetworkNotAllowed
    NetworkNotAllowed = 32,
    /// nick=NetworkPin
    NetworkPin = 40,
    /// nick=NetworkPuk
    NetworkPuk = 41,
    /// nick=NetworkSubsetPin
    NetworkSubsetPin = 42,
    /// nick=NetworkSubsetPuk
    NetworkSubsetPuk = 43,
    /// nick=ServicePin
    ServicePin = 44,
    /// nick=ServicePuk
    ServicePuk = 45,
    /// nick=CorpPin
    CorpPin = 46,
    /// nick=CorpPuk
    CorpPuk = 47,
    /// nick=HiddenKeyRequired
    HiddenKeyRequired = 48,
    /// nick=EapMethodNotSupported
    EapMethodNotSupported = 49,
    /// nick=IncorrectParameters
    IncorrectParameters = 50,
    /// nick=CommandDisabled
    CommandDisabled = 51,
    /// nick=CommandAborted
    CommandAborted = 52,
    /// nick=NotAttachedRestricted
    NotAttachedRestricted = 53,
    /// nick=NotAllowedEmergencyOnly
    NotAllowedEmergencyOnly = 54,
    /// nick=NotAllowedRestricted
    NotAllowedRestricted = 55,
    /// nick=FixedDialNumberOnly
    FixedDialNumberOnly = 56,
    /// nick=TemporarilyOutOfService
    TemporarilyOutOfService = 57,
    /// nick=LanguageOrAlphabetNotSupported
    LanguageOrAlphabetNotSupported = 58,
    /// nick=UnexpectedDataValue
    UnexpectedDataValue = 59,
    /// nick=SystemFailure
    SystemFailure = 60,
    /// nick=DataMissing
    DataMissing = 61,
    /// nick=CallBarred
    CallBarred = 62,
    /// nick=MessageWaitingIndicationSubscriptionFailure
    MessageWaitingIndicationSubscriptionFailure = 63,
    /// nick=Unknown
    Unknown = 100,
    /// nick=ImsiUnknownInHss
    ImsiUnknownInHss = 102,
    /// nick=IllegalUe
    IllegalUe = 103,
    /// nick=ImsiUnknownInVlr
    ImsiUnknownInVlr = 104,
    /// nick=ImeiNotAccepted
    ImeiNotAccepted = 105,
    /// nick=IllegalMe
    IllegalMe = 106,
    /// nick=PsServicesNotAllowed
    PsServicesNotAllowed = 107,
    /// nick=PsAndNonPsServicesNotAllowed
    PsAndNonPsServicesNotAllowed = 108,
    /// nick=UeIdentityNotDerivedFromNetwork
    UeIdentityNotDerivedFromNetwork = 109,
    /// nick=ImplicitlyDetached
    ImplicitlyDetached = 110,
    /// nick=PlmnNotAllowed
    PlmnNotAllowed = 111,
    /// nick=AreaNotAllowed
    AreaNotAllowed = 112,
    /// nick=RoamingNotAllowedInArea
    RoamingNotAllowedInArea = 113,
    /// nick=PsServicesNotAllowedInPlmn
    PsServicesNotAllowedInPlmn = 114,
    /// nick=NoCellsInArea
    NoCellsInArea = 115,
    /// nick=MscTemporarilyNotReachable
    MscTemporarilyNotReachable = 116,
    /// nick=NetworkFailureAttach
    NetworkFailureAttach = 117,
    /// nick=CsDomainUnavailable
    CsDomainUnavailable = 118,
    /// nick=EsmFailure
    EsmFailure = 119,
    /// nick=Congestion
    Congestion = 122,
    /// nick=MbmsBearerCapabilitiesInsufficientForService
    MbmsBearerCapabilitiesInsufficientForService = 124,
    /// nick=NotAuthorizedForCsg
    NotAuthorizedForCsg = 125,
    /// nick=InsufficientResources
    InsufficientResources = 126,
    /// nick=MissingOrUnknownApn
    MissingOrUnknownApn = 127,
    /// nick=UnknownPdpAddressOrType
    UnknownPdpAddressOrType = 128,
    /// nick=UserAuthenticationFailed
    UserAuthenticationFailed = 129,
    /// nick=ActivationRejectedByGgsnOrGw
    ActivationRejectedByGgsnOrGw = 130,
    /// nick=ActivationRejectedUnspecified
    ActivationRejectedUnspecified = 131,
    /// nick=ServiceOptionNotSupported
    ServiceOptionNotSupported = 132,
    /// nick=ServiceOptionNotSubscribed
    ServiceOptionNotSubscribed = 133,
    /// nick=ServiceOptionOutOfOrder
    ServiceOptionOutOfOrder = 134,
    /// nick=NsapiOrPtiAlreadyInUse
    NsapiOrPtiAlreadyInUse = 135,
    /// nick=RegularDeactivation
    RegularDeactivation = 136,
    /// nick=QosNotAccepted
    QosNotAccepted = 137,
    /// nick=CallCannotBeIdentified
    CallCannotBeIdentified = 138,
    /// nick=CsServiceTemporarilyUnavailable
    CsServiceTemporarilyUnavailable = 139,
    /// nick=FeatureNotSupported
    FeatureNotSupported = 140,
    /// nick=SemanticErrorInTftOperation
    SemanticErrorInTftOperation = 141,
    /// nick=SyntacticalErrorInTftOperation
    SyntacticalErrorInTftOperation = 142,
    /// nick=UnknownPdpContext
    UnknownPdpContext = 143,
    /// nick=SemanticErrorsInPacketFilter
    SemanticErrorsInPacketFilter = 144,
    /// nick=SyntacticalErrorsInPacketFilter
    SyntacticalErrorInPacketFilter = 145,
    /// nick=PdpContextWithoutTftAlreadyActivated
    PdpContextWithoutTftAlreadyActivated = 146,
    /// nick=MulticastGroupMembershipTimeout
    MulticastGroupMembershipTimeout = 147,
    /// nick=GprsUnknown
    GprsUnknown = 148,
    /// nick=PdpAuthFailure
    PdpAuthFailure = 149,
    /// nick=InvalidMobileClass
    InvalidMobileClass = 150,
    /// nick=LastPdnDisconnectionNotAllowedLegacy
    LastPdnDisconnectionNotAllowedLegacy = 151,
    /// nick=LastPdnDisconnectionNotAllowed
    LastPdnDisconnectionNotAllowed = 171,
    /// nick=SemanticallyIncorrectMessage
    SemanticallyIncorrectMessage = 172,
    /// nick=InvalidMandatoryInformation
    InvalidMandatoryInformation = 173,
    /// nick=MessageTypeNotImplemented
    MessageTypeNotImplemented = 174,
    /// nick=ConditionalIeError
    ConditionalIeError = 175,
    /// nick=UnspecifiedProtocolError
    UnspecifiedProtocolError = 176,
    /// nick=OperatorDeterminedBarring
    OperatorDeterminedBarring = 177,
    /// nick=MaximumNumberOfBearersReached
    MaximumNumberOfBearersReached = 178,
    /// nick=RequestedApnNotSupported
    RequestedApnNotSupported = 179,
    /// nick=RequestRejectedBcmViolation
    RequestRejectedBcmViolation = 180,
    /// nick=UnsupportedQciOr5qiValue
    UnsupportedQciOr5QiValue = 181,
    /// nick=UserDataViaControlPlaneCongested
    UserDataViaControlPlaneCongested = 182,
    /// nick=SmsProvidedViaGprsInRoutingArea
    SmsProvidedViaGprsInRoutingArea = 183,
    /// nick=InvalidPtiValue
    InvalidPtiValue = 184,
    /// nick=NoBearerActivated
    NoBearerActivated = 185,
    /// nick=MessageNotCompatibleWithProtocolState
    MessageNotCompatibleWithProtocolState = 186,
    /// nick=RecoveryOnTimerExpiry
    RecoveryOnTimerExpiry = 187,
    /// nick=InvalidTransactionIdValue
    InvalidTransactionIdValue = 188,
    /// nick=ServiceOptionNotAuthorizedInPlmn
    ServiceOptionNotAuthorizedInPlmn = 189,
    /// nick=NetworkFailureActivation
    NetworkFailureActivation = 190,
    /// nick=ReactivationRequested
    ReactivationRequested = 191,
    /// nick=Ipv4OnlyAllowed
    Ipv4OnlyAllowed = 192,
    /// nick=Ipv6OnlyAllowed
    Ipv6OnlyAllowed = 193,
    /// nick=SingleAddressBearersOnlyAllowed
    SingleAddressBearersOnlyAllowed = 194,
    /// nick=CollisionWithNetworkInitiatedRequest
    CollisionWithNetworkInitiatedRequest = 195,
    /// nick=Ipv4v6OnlyAllowed
    Ipv4V6OnlyAllowed = 196,
    /// nick=NonIpOnlyAllowed
    NonIpOnlyAllowed = 197,
    /// nick=BearerHandlingUnsupported
    BearerHandlingUnsupported = 198,
    /// nick=ApnRestrictionIncompatible
    ApnRestrictionIncompatible = 199,
    /// nick=MultipleAccessToPdnConnectionNotAllowed
    MultipleAccessToPdnConnectionNotAllowed = 200,
    /// nick=EsmInformationNotReceived
    EsmInformationNotReceived = 201,
    /// nick=PdnConnectionNonexistent
    PdnConnectionNonexistent = 202,
    /// nick=MultiplePdnConnectionSameApnNotAllowed
    MultiplePdnConnectionSameApnNotAllowed = 203,
    /// nick=SevereNetworkFailure
    SevereNetworkFailure = 204,
    /// nick=InsufficientResourcesForSliceAndDnn
    InsufficientResourcesForSliceAndDnn = 205,
    /// nick=UnsupportedSscMode
    UnsupportedSscMode = 206,
    /// nick=InsufficientResourcesForSlice
    InsufficientResourcesForSlice = 207,
    /// nick=MessageTypeNotCompatibleWithProtocolState
    MessageTypeNotCompatibleWithProtocolState = 208,
    /// nick=IeNotImplemented
    IeNotImplemented = 209,
    /// nick=N1ModeNotAllowed
    N1ModeNotAllowed = 210,
    /// nick=RestrictedServiceArea
    RestrictedServiceArea = 211,
    /// nick=LadnUnavailable
    LadnUnavailable = 212,
    /// nick=MissingOrUnknownDnnInSlice
    MissingOrUnknownDnnInSlice = 213,
    /// nick=NkgsiAlreadyInUse
    NgksiAlreadyInUse = 214,
    /// nick=PayloadNotForwarded
    PayloadNotForwarded = 215,
    /// nick=Non3gppAccessTo5gcnNotAllowed
    Non3GppAccessTo5GcnNotAllowed = 216,
    /// nick=ServingNetworkNotAuthorized
    ServingNetworkNotAuthorized = 217,
    /// nick=DnnNotSupportedInSlice
    DnnNotSupportedInSlice = 218,
    /// nick=InsufficientUserPlaneResourcesForPduSession
    InsufficientUserPlaneResourcesForPduSessio = 219,
    /// nick=OutOfLadnServiceArea
    OutOfLadnServiceArea = 220,
    /// nick=PtiMismatch
    PtiMismatch = 221,
    /// nick=MaxDataRateForUserPlaneIntegrityTooLow
    MaxDataRateForUserPlaneIntegrityTooLow = 222,
    /// nick=SemanticErrorInQosOperation
    SemanticErrorInQosOperation = 223,
    /// nick=SyntacticalErrorInQosOperation
    SyntacticalErrorInQosOperation = 224,
    /// nick=InvalidMappedEpsBearerIdentity
    InvalidMappedEpsBearerIdentity = 225,
    /// nick=RedirectionTo5gcnRequired
    RedirectionTo5GcnRequired = 226,
    /// nick=RedirectionToEpcRequired
    RedirectionToEpcRequired = 227,
    /// nick=TemporarilyUnauthorizedForSnpn
    TemporarilyUnauthorizedForSnpn = 228,
    /// nick=PermanentlyUnauthorizedForSnpn
    PermanentlyUnauthorizedForSnpn = 229,
    /// nick=EthernetOnlyAllowed
    EthernetOnlyAllowed = 230,
    /// nick=UnauthorizedForCag
    UnauthorizedForCag = 231,
    /// nick=NoNetworkSlicesAvailable
    NoNetworkSlicesAvailable = 232,
    /// nick=WirelineAccessAreaNotAllowed
    WirelineAccessAreaNotAllowed = 233,
}

impl Debug for CmeError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "CME error");

        Ok(())
    }
}

impl From<u16> for CmeError {
    fn from(v: u16) -> Self {
        match v {
            0 => Self::PhoneFailure,
            1 => Self::NoConnection,
            2 => Self::LinkReserved,
            3 => Self::NotAllowed,
            4 => Self::NotSupported,
            5 => Self::PhSimPin,
            6 => Self::PhFsimPin,
            7 => Self::PhFsimPuk,
            10 => Self::SimNotInserted,
            11 => Self::SimPin,
            12 => Self::SimPuk,
            13 => Self::SimFailure,
            14 => Self::SimBusy,
            15 => Self::SimWrong,
            16 => Self::IncorrectPassword,
            17 => Self::SimPin2,
            18 => Self::SimPuk2,
            20 => Self::MemoryFull,
            21 => Self::InvalidIndex,
            22 => Self::NotFound,
            23 => Self::MemoryFailure,
            24 => Self::TextTooLong,
            25 => Self::InvalidChars,
            26 => Self::DialStringTooLong,
            27 => Self::DialStringInvalid,
            30 => Self::NoNetwork,
            31 => Self::NetworkTimeout,
            32 => Self::NetworkNotAllowed,
            40 => Self::NetworkPin,
            41 => Self::NetworkPuk,
            42 => Self::NetworkSubsetPin,
            43 => Self::NetworkSubsetPuk,
            44 => Self::ServicePin,
            45 => Self::ServicePuk,
            46 => Self::CorpPin,
            47 => Self::CorpPuk,
            48 => Self::HiddenKeyRequired,
            49 => Self::EapMethodNotSupported,
            50 => Self::IncorrectParameters,
            51 => Self::CommandDisabled,
            52 => Self::CommandAborted,
            53 => Self::NotAttachedRestricted,
            54 => Self::NotAllowedEmergencyOnly,
            55 => Self::NotAllowedRestricted,
            56 => Self::FixedDialNumberOnly,
            57 => Self::TemporarilyOutOfService,
            58 => Self::LanguageOrAlphabetNotSupported,
            59 => Self::UnexpectedDataValue,
            60 => Self::SystemFailure,
            61 => Self::DataMissing,
            62 => Self::CallBarred,
            63 => Self::MessageWaitingIndicationSubscriptionFailure,
            // 100 => Self::Unknown,
            102 => Self::ImsiUnknownInHss,
            103 => Self::IllegalUe,
            104 => Self::ImsiUnknownInVlr,
            105 => Self::ImeiNotAccepted,
            106 => Self::IllegalMe,
            107 => Self::PsServicesNotAllowed,
            108 => Self::PsAndNonPsServicesNotAllowed,
            109 => Self::UeIdentityNotDerivedFromNetwork,
            110 => Self::ImplicitlyDetached,
            111 => Self::PlmnNotAllowed,
            112 => Self::AreaNotAllowed,
            113 => Self::RoamingNotAllowedInArea,
            114 => Self::PsServicesNotAllowedInPlmn,
            115 => Self::NoCellsInArea,
            116 => Self::MscTemporarilyNotReachable,
            117 => Self::NetworkFailureAttach,
            118 => Self::CsDomainUnavailable,
            119 => Self::EsmFailure,
            122 => Self::Congestion,
            124 => Self::MbmsBearerCapabilitiesInsufficientForService,
            125 => Self::NotAuthorizedForCsg,
            126 => Self::InsufficientResources,
            127 => Self::MissingOrUnknownApn,
            128 => Self::UnknownPdpAddressOrType,
            129 => Self::UserAuthenticationFailed,
            130 => Self::ActivationRejectedByGgsnOrGw,
            131 => Self::ActivationRejectedUnspecified,
            132 => Self::ServiceOptionNotSupported,
            133 => Self::ServiceOptionNotSubscribed,
            134 => Self::ServiceOptionOutOfOrder,
            135 => Self::NsapiOrPtiAlreadyInUse,
            136 => Self::RegularDeactivation,
            137 => Self::QosNotAccepted,
            138 => Self::CallCannotBeIdentified,
            139 => Self::CsServiceTemporarilyUnavailable,
            140 => Self::FeatureNotSupported,
            141 => Self::SemanticErrorInTftOperation,
            142 => Self::SyntacticalErrorInTftOperation,
            143 => Self::UnknownPdpContext,
            144 => Self::SemanticErrorsInPacketFilter,
            145 => Self::SyntacticalErrorInPacketFilter,
            146 => Self::PdpContextWithoutTftAlreadyActivated,
            147 => Self::MulticastGroupMembershipTimeout,
            148 => Self::GprsUnknown,
            149 => Self::PdpAuthFailure,
            150 => Self::InvalidMobileClass,
            151 => Self::LastPdnDisconnectionNotAllowedLegacy,
            171 => Self::LastPdnDisconnectionNotAllowed,
            172 => Self::SemanticallyIncorrectMessage,
            173 => Self::InvalidMandatoryInformation,
            174 => Self::MessageTypeNotImplemented,
            175 => Self::ConditionalIeError,
            176 => Self::UnspecifiedProtocolError,
            177 => Self::OperatorDeterminedBarring,
            178 => Self::MaximumNumberOfBearersReached,
            179 => Self::RequestedApnNotSupported,
            180 => Self::RequestRejectedBcmViolation,
            181 => Self::UnsupportedQciOr5QiValue,
            182 => Self::UserDataViaControlPlaneCongested,
            183 => Self::SmsProvidedViaGprsInRoutingArea,
            184 => Self::InvalidPtiValue,
            185 => Self::NoBearerActivated,
            186 => Self::MessageNotCompatibleWithProtocolState,
            187 => Self::RecoveryOnTimerExpiry,
            188 => Self::InvalidTransactionIdValue,
            189 => Self::ServiceOptionNotAuthorizedInPlmn,
            190 => Self::NetworkFailureActivation,
            191 => Self::ReactivationRequested,
            192 => Self::Ipv4OnlyAllowed,
            193 => Self::Ipv6OnlyAllowed,
            194 => Self::SingleAddressBearersOnlyAllowed,
            195 => Self::CollisionWithNetworkInitiatedRequest,
            196 => Self::Ipv4V6OnlyAllowed,
            197 => Self::NonIpOnlyAllowed,
            198 => Self::BearerHandlingUnsupported,
            199 => Self::ApnRestrictionIncompatible,
            200 => Self::MultipleAccessToPdnConnectionNotAllowed,
            201 => Self::EsmInformationNotReceived,
            202 => Self::PdnConnectionNonexistent,
            203 => Self::MultiplePdnConnectionSameApnNotAllowed,
            204 => Self::SevereNetworkFailure,
            205 => Self::InsufficientResourcesForSliceAndDnn,
            206 => Self::UnsupportedSscMode,
            207 => Self::InsufficientResourcesForSlice,
            208 => Self::MessageTypeNotCompatibleWithProtocolState,
            209 => Self::IeNotImplemented,
            210 => Self::N1ModeNotAllowed,
            211 => Self::RestrictedServiceArea,
            212 => Self::LadnUnavailable,
            213 => Self::MissingOrUnknownDnnInSlice,
            214 => Self::NgksiAlreadyInUse,
            215 => Self::PayloadNotForwarded,
            216 => Self::Non3GppAccessTo5GcnNotAllowed,
            217 => Self::ServingNetworkNotAuthorized,
            218 => Self::DnnNotSupportedInSlice,
            219 => Self::InsufficientUserPlaneResourcesForPduSessio,
            220 => Self::OutOfLadnServiceArea,
            221 => Self::PtiMismatch,
            222 => Self::MaxDataRateForUserPlaneIntegrityTooLow,
            223 => Self::SemanticErrorInQosOperation,
            224 => Self::SyntacticalErrorInQosOperation,
            225 => Self::InvalidMappedEpsBearerIdentity,
            226 => Self::RedirectionTo5GcnRequired,
            227 => Self::RedirectionToEpcRequired,
            228 => Self::TemporarilyUnauthorizedForSnpn,
            229 => Self::PermanentlyUnauthorizedForSnpn,
            230 => Self::EthernetOnlyAllowed,
            231 => Self::UnauthorizedForCag,
            232 => Self::NoNetworkSlicesAvailable,
            233 => Self::WirelineAccessAreaNotAllowed,
            _ => Self::Unknown,
        }
    }
}

impl CmeError {
    pub const fn from_msg(s: &[u8]) -> Self {
        Self::Unknown
    }
}

#[cfg(feature = "defmt")]
impl<'a> defmt::Format for CmeError {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(f, "CME Error");
    }
}
