[package]
name = "atat"
version = "0.18.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AT Parser for serial based device crates"
readme = "../README.md"
keywords = ["arm", "cortex-m", "AT", "no-std", "embedded-hal-driver"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/atat"
edition = "2021"
documentation = "https://docs.rs/atat"

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "atat"

[[example]]
name = "rtic"
required-features = ["defmt"]

[[example]]
name = "cortex-m-rt"
required-features = ["defmt"]

[dependencies]
embedded-hal = "0.2.7"
fugit = "0.3.3"
fugit-timer = "0.1.2"
heapless = { version = "^0.7", features = ["serde"] }
bbqueue = "0.5"
serde_at = { path = "../serde_at", version = "^0.18.0", optional = true }
atat_derive = { path = "../atat_derive", version = "^0.18.0", optional = true }
serde_bytes = { version = "0.11.5", default-features = false, optional = true }
heapless-bytes = { version = "0.3.0", optional = true }

nom = { version = "^7.1", default-features = false }

log = { version = "^0.4", default-features = false, optional = true }
defmt = { version = "^0.3", optional = true }
nb = "1.0.0"

[dev-dependencies]
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.1"
cortex-m-rtic = "1.0.0"
defmt-rtt = "0.3.1"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
dwt-systick-monotonic = "1.0.0"
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy", rev = "99284b8", features = [
    "stm32l475vg",
    "unstable-traits",
    "unstable-pac",
] }

[features]
default = ["derive", "bytes"]
derive = ["atat_derive", "serde_at"]
custom-error-messages = []

bytes = ["heapless-bytes", "serde_bytes"]

std = ["serde_at/std", "nom/std"]
